### ISSUE TITLE
Code Issue Review

### ISSUE THREAD

**Issue by wattob** [thomad74/portfolioProject#1]
### Date of the review: November 15, 2018
Inspection rate: about 10 lines per minute around 10 minutes total for review
Defect rate: 2 bugs found in the operators in 10 minutes of review
Defect density:  1 bug per 50 line 
### Checklist
- [ ] Code Formatting
There isn't a style guide that your code is following.
- [x] Coding Best Practices
- [x] Code Readability
The code is well organized
- [x] Code Testability
- [ ] Code Reliability
Some of your operators fail to work
- [ ] Usability
There are some errors

**Comment by thomad74** [comment]
After the review of my code, I have decided to scrap this idea of a calculator, and create some sort of interactive game using the pygame library in Python. I am choosing to do this because I am more interested in creating an interactive game over a calculator, and I thought of a creative idea for a game.

**Comment by thomad74** [comment]
I took this issue into consideration when implementing my code, and was sure to implement a Travis file that follows a specific style guide. Also, I focused on code reliability and usability like you mentioned before, and I think I fixed all the bugs in my code so that it will work properly.
